# Generated by Django 5.1 on 2025-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
